// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewaqqzyzfrfjstqfdubf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YXFxenl6ZnJmanN0cWZkdWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzkwODEsImV4cCI6MjA1MjU1NTA4MX0.BSswGLCRAxKVEe_knGlz1YXjANY747VHoR5X2s88OwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);